// auto-generated by C.E.W.T.
// DO NOT EDIT BY HAND!!
export class SwapFromComponentRefs {
	#element: HTMLElement | ShadowRoot;
	constructor(element: HTMLElement | ShadowRoot) {
		this.#element = element;
	}
	#balanceAmount?: HTMLSpanElement;
	get balanceAmount() {
		if (this.#balanceAmount === undefined) {
			this.#balanceAmount = this.#element.querySelector("[cewt-ref=\"balance-amount\"]:not(:scope [is] *)")!;
		}
		return this.#balanceAmount;
	}
	#dropdown?: HTMLButtonElement;
	get dropdown() {
		if (this.#dropdown === undefined) {
			this.#dropdown = this.#element.querySelector("[cewt-ref=\"dropdown\"]:not(:scope [is] *)")!;
		}
		return this.#dropdown;
	}
	#selectedAmount?: HTMLInputElement;
	get selectedAmount() {
		if (this.#selectedAmount === undefined) {
			this.#selectedAmount = this.#element.querySelector("[cewt-ref=\"selected-amount\"]:not(:scope [is] *)")!;
		}
		return this.#selectedAmount;
	}
	#amountSlider?: HTMLInputElement;
	get amountSlider() {
		if (this.#amountSlider === undefined) {
			this.#amountSlider = this.#element.querySelector("[cewt-ref=\"amount-slider\"]:not(:scope [is] *)")!;
		}
		return this.#amountSlider;
	}
	#currentPercentage?: HTMLSpanElement;
	get currentPercentage() {
		if (this.#currentPercentage === undefined) {
			this.#currentPercentage = this.#element.querySelector("[cewt-ref=\"current-percentage\"]:not(:scope [is] *)")!;
		}
		return this.#currentPercentage;
	}
}
let _templateSwapFromComponent: HTMLTemplateElement | null = null;
function getSwapFromComponentTemplate(): HTMLTemplateElement {
	if (_templateSwapFromComponent == null) {
		 _templateSwapFromComponent = document.createElement("template")
		 _templateSwapFromComponent.innerHTML = "\n  <div class=\"labels-row\">\n    <span>From:</span>\n    <div>\n      Balance: <span cewt-ref=\"balance-amount\">0</span>\n    </div>\n  </div>\n\n  <div class=\"fantasy-input-group\">\n    <button is=\"token-dropdown-component\" id=\"from-token-dropdown\" cewt-ref=\"dropdown\"></button>\n\n    <div class=\"slider-container\">\n      <div class=\"slider-amounts\">\n        <input cewt-ref=\"selected-amount\" type=\"text\" value=\"0\">\n        <!-- <span cewt-ref=\"selected-converted-amount\" class=\"text-fantasy converted-amount\">~ $0</span> -->\n      </div>\n\n      <div class=\"slider\">\n        <input type=\"range\" list=\"token_range_tickmarks\" min=\"0\" max=\"100\" value=\"0\" cewt-ref=\"amount-slider\">\n        <span cewt-ref=\"current-percentage\" class=\"text-fantasy\">0%</span>\n      </div>\n\n      <datalist id=\"token_range_tickmarks\">\n        <option value=\"25\"></option>\n        <option value=\"50\"></option>\n        <option value=\"75\"></option>\n        <option value=\"90\"></option>\n        <option value=\"100\"></option>\n      </datalist>\n    </div>\n  </div>\n";
	}
	return _templateSwapFromComponent;
}
export class SwapFromComponentAutogen extends HTMLDivElement {
	readonly refs: SwapFromComponentRefs;
	static get observedAttributes() {
		return ["token", "tokens"];
	}
	#attributeTokenValue: string | null = null;
	get token(): string | null {
		return this.#attributeTokenValue;
	}
	set token(v: string | null) {
		if (v == null) {
			this.removeAttribute("token");
		}else{
			this.setAttribute("token", v);
		}
	}
	protected onTokenChanged(oldValue: string | null, newValue: string | null) {
		// To be overridden by child class
	}
	#attributeTokensValue: string | null = null;
	get tokens(): string | null {
		return this.#attributeTokensValue;
	}
	set tokens(v: string | null) {
		if (v == null) {
			this.removeAttribute("tokens");
		}else{
			this.setAttribute("tokens", v);
		}
	}
	protected onTokensChanged(oldValue: string | null, newValue: string | null) {
		// To be overridden by child class
	}
	attributeChangedCallback(name: string, oldValue: string | null, newValue: string | null) {
		switch(name) {
			case "token":
				this.#attributeTokenValue = newValue;
				this.onTokenChanged(oldValue, newValue);
				break;
			case "tokens":
				this.#attributeTokensValue = newValue;
				this.onTokensChanged(oldValue, newValue);
				break;
			default:
				// Shouldn't happen
		}
	}
	constructor() {
		super();
		if (this.childElementCount == 0) {
			this.appendChild(
				getSwapFromComponentTemplate()
					.content
					.cloneNode(true)
			);
		}
		this.setAttribute("is", "swap-from-component"); // allow for easy query selecting
		this.refs = new SwapFromComponentRefs(this);
	}
	connectedCallback() {
		// To be overridden by child class
	}
	disconnectedCallback() {
		// To be overridden by child class
	}
	adoptedCallback() {
		// To be overridden by child class
	}
	public static registerElement() {
		customElements.define("swap-from-component", this, { extends: "div"});
	}
}
