/**
 * DO NOT EDIT YOURSELF!
 * This file was automatically generated by json-schema-to-typescript.
 * The source schema json was automatically generated by cosmwasm-schema during the contract build.
 * The Rust code is the source of truth! Re-run the whole build if this file is outdated.
 **/

export type QueryMsg =
  | {
      balance: {
        address: string;
      };
    }
  | {
      token_info: {};
    }
  | {
      minter: {};
    }
  | {
      allowance: {
        owner: string;
        spender: string;
      };
    }
  | {
      all_allowances: {
        limit?: number | null;
        owner: string;
        start_after?: string | null;
      };
    }
  | {
      all_spender_allowances: {
        limit?: number | null;
        spender: string;
        start_after?: string | null;
      };
    }
  | {
      all_accounts: {
        limit?: number | null;
        start_after?: string | null;
      };
    }
  | {
      marketing_info: {};
    }
  | {
      download_logo: {};
    };
