[workspace]
resolver = "2"
members = [
  "packages/*",
  "contracts/factory",
  "contracts/pair",
  "contracts/router",
  "contracts/token",
  "templates/*",
  "contracts/periphery/*",
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
strip = true
