// auto-generated by C.E.W.T.
// DO NOT EDIT BY HAND!!
import { TokenDisplayElement } from "@crownfi/sei-webui-utils";
export class CurrencySelectorRefs {
	#element: HTMLElement | ShadowRoot;
	constructor(element: HTMLElement | ShadowRoot) {
		this.#element = element;
	}
	#selectedCurrency?: TokenDisplayElement;
	get selectedCurrency() {
		if (this.#selectedCurrency === undefined) {
			this.#selectedCurrency = this.#element.querySelector("[cewt-ref=\"selected-currency\"]:not(:scope [is] *)")!;
		}
		return this.#selectedCurrency;
	}
	#currencySelector?: HTMLElement;
	get currencySelector() {
		if (this.#currencySelector === undefined) {
			this.#currencySelector = this.#element.querySelector("[cewt-ref=\"currency-selector\"]:not(:scope [is] *)")!;
		}
		return this.#currencySelector;
	}
}
let _templateCurrencySelector: HTMLTemplateElement | null = null;
function getCurrencySelectorTemplate(): HTMLTemplateElement {
	if (_templateCurrencySelector == null) {
		 _templateCurrencySelector = document.createElement("template")
		 _templateCurrencySelector.innerHTML = "\n  <button class=\"fantasy-ornamental\">\n    <span is=\"token-display\" cewt-ref=\"selected-currency\"></span>\n  </button>\n\n  <dropdown-menu click-trigger=\"primary\" cewt-ref=\"currency-selector\" linked-elements=\"[is=\'currency-selector\']:has(#this)\">\n  </dropdown-menu>\n";
	}
	return _templateCurrencySelector;
}
export class CurrencySelectorAutogen extends HTMLDivElement {
	readonly refs: CurrencySelectorRefs;
	constructor() {
		super();
		if (this.childElementCount == 0) {
			this.appendChild(
				getCurrencySelectorTemplate()
					.content
					.cloneNode(true)
			);
		}
		this.setAttribute("is", "currency-selector"); // allow for easy query selecting
		this.refs = new CurrencySelectorRefs(this);
	}
	connectedCallback() {
		// To be overridden by child class
	}
	disconnectedCallback() {
		// To be overridden by child class
	}
	adoptedCallback() {
		// To be overridden by child class
	}
	public static registerElement() {
		customElements.define("currency-selector", this, { extends: "div"});
	}
}
