/* eslint-disable */
/**
 * This file was automatically generated by crownfi-sei-sdk-autogen.
 * DO NOT MODIFY IT BY HAND.
 * The Rust definition of the associated structs is the source of truth!!
 */
import {Addr, CW20WrapperExecMsg, Cw20ReceiveMsg, Empty, TokenWrapperQueryMsg} from "./types.js";
import {Coin} from "@cosmjs/amino";
import {ExecuteInstruction} from "@cosmjs/cosmwasm-stargate";
import {ContractBase} from "@crownfi/sei-utils";
export class Cw20WrapperContract extends ContractBase {
	queryEmpty(): Promise<Empty> {
		const msg = {"empty": {}} satisfies TokenWrapperQueryMsg;
		return this.query(msg);
	}
	buildReceiveIx(args: Cw20ReceiveMsg, funds?: Coin[]): ExecuteInstruction {
		const msg = {"receive": args} satisfies CW20WrapperExecMsg;
		return this.executeIx(msg, funds);
	}
	buildUnwrapIx(args: {"receiver"?: Addr | null} = {}, funds?: Coin[]): ExecuteInstruction {
		const msg = {"unwrap": args} satisfies CW20WrapperExecMsg;
		return this.executeIx(msg, funds);
	}
}
