/* eslint-disable */
/**
 * This file was automatically generated by crownfi-sei-sdk-autogen.
 * DO NOT MODIFY IT BY HAND.
 * The Rust definition of the associated structs is the source of truth!!
 */
import {Addr, ERC20WrapperExecMsg, Empty, TokenWrapperQueryMsg, Uint128} from "./types.js";
import {Coin} from "@cosmjs/amino";
import {ExecuteInstruction} from "@cosmjs/cosmwasm-stargate";
import {ContractBase} from "@crownfi/sei-utils";
export class Erc20WrapperContract extends ContractBase {
	queryEmpty(): Promise<Empty> {
		const msg = {"empty": {}} satisfies TokenWrapperQueryMsg;
		return this.query(msg);
	}
	buildWrapIx(args: {"amount": Uint128, "recipient": string, "token_addr": string}, funds?: Coin[]): ExecuteInstruction {
		const msg = {"wrap": args} satisfies ERC20WrapperExecMsg;
		return this.executeIx(msg, funds);
	}
	buildUnwrapIx(args: {"recipient"?: Addr | null} = {}, funds?: Coin[]): ExecuteInstruction {
		const msg = {"unwrap": args} satisfies ERC20WrapperExecMsg;
		return this.executeIx(msg, funds);
	}
}
