/* eslint-disable */
/**
 * This file was automatically generated by crownfi-sei-sdk-autogen.
 * DO NOT MODIFY IT BY HAND.
 * The Rust definition of the associated structs is the source of truth!!
 */
import {Addr, Decimal, SwapRouterExecuteMsg, SwapRouterExpectation, SwapRouterQueryMsg, SwapRouterSimulateSwapsResponse} from "./types.js";
import {Coin} from "@cosmjs/amino";
import {ExecuteInstruction} from "@cosmjs/cosmwasm-stargate";
import {ContractBase} from "@crownfi/sei-utils";
export class SwapRouterContract extends ContractBase {
	querySimulateSwaps(args: {"offer": Coin, "swappers": Addr[]}): Promise<SwapRouterSimulateSwapsResponse> {
		const msg = {"simulate_swaps": args} satisfies SwapRouterQueryMsg;
		return this.query(msg);
	}
	buildExecuteSwapsIx(args: {"expectation"?: SwapRouterExpectation | null, "intermediate_slippage_tolerance"?: Decimal | null, "receiver"?: Addr | null, "swappers": Addr[], "unwrapper"?: Addr | null}, funds?: Coin[]): ExecuteInstruction {
		const msg = {"execute_swaps": args} satisfies SwapRouterExecuteMsg;
		return this.executeIx(msg, funds);
	}
	buildNextStepIx(funds?: Coin[]): ExecuteInstruction {
		const msg = {"next_step": {}} satisfies SwapRouterExecuteMsg;
		return this.executeIx(msg, funds);
	}
}
