// auto-generated by C.E.W.T.
// DO NOT EDIT BY HAND!!
import { TokenDisplayElement } from "@crownfi/sei-webui-utils";
export class PoolItemComponentRefs {
	#element: HTMLElement | ShadowRoot;
	constructor(element: HTMLElement | ShadowRoot) {
		this.#element = element;
	}
	#poolsFrom?: TokenDisplayElement;
	get poolsFrom() {
		if (this.#poolsFrom === undefined) {
			this.#poolsFrom = this.#element.querySelector("[cewt-ref=\"poolsFrom\"]:not(:scope [is] *)")!;
		}
		return this.#poolsFrom;
	}
	#poolsTo?: TokenDisplayElement;
	get poolsTo() {
		if (this.#poolsTo === undefined) {
			this.#poolsTo = this.#element.querySelector("[cewt-ref=\"poolsTo\"]:not(:scope [is] *)")!;
		}
		return this.#poolsTo;
	}
	#exchangeRateFrom?: TokenDisplayElement;
	get exchangeRateFrom() {
		if (this.#exchangeRateFrom === undefined) {
			this.#exchangeRateFrom = this.#element.querySelector("[cewt-ref=\"exchangeRateFrom\"]:not(:scope [is] *)")!;
		}
		return this.#exchangeRateFrom;
	}
	#exchangeRateTo?: TokenDisplayElement;
	get exchangeRateTo() {
		if (this.#exchangeRateTo === undefined) {
			this.#exchangeRateTo = this.#element.querySelector("[cewt-ref=\"exchangeRateTo\"]:not(:scope [is] *)")!;
		}
		return this.#exchangeRateTo;
	}
	#totalDepositsFrom?: TokenDisplayElement;
	get totalDepositsFrom() {
		if (this.#totalDepositsFrom === undefined) {
			this.#totalDepositsFrom = this.#element.querySelector("[cewt-ref=\"totalDepositsFrom\"]:not(:scope [is] *)")!;
		}
		return this.#totalDepositsFrom;
	}
	#totalDepositsTo?: TokenDisplayElement;
	get totalDepositsTo() {
		if (this.#totalDepositsTo === undefined) {
			this.#totalDepositsTo = this.#element.querySelector("[cewt-ref=\"totalDepositsTo\"]:not(:scope [is] *)")!;
		}
		return this.#totalDepositsTo;
	}
	#feeRate?: HTMLSpanElement;
	get feeRate() {
		if (this.#feeRate === undefined) {
			this.#feeRate = this.#element.querySelector("[cewt-ref=\"feeRate\"]:not(:scope [is] *)")!;
		}
		return this.#feeRate;
	}
	#apy?: HTMLSpanElement;
	get apy() {
		if (this.#apy === undefined) {
			this.#apy = this.#element.querySelector("[cewt-ref=\"apy\"]:not(:scope [is] *)")!;
		}
		return this.#apy;
	}
}
let _templatePoolItemComponent: HTMLTemplateElement | null = null;
function getPoolItemComponentTemplate(): HTMLTemplateElement {
	if (_templatePoolItemComponent == null) {
		 _templatePoolItemComponent = document.createElement("template")
		 _templatePoolItemComponent.innerHTML = "\n  <td class=\"overlapping-icons\">\n    #\n  </td>\n\n  <td>\n    <div class=\"pools\">\n      <span class=\"badge\" is=\"token-display\" cewt-ref=\"poolsFrom\"></span>\n      <span class=\"badge\" is=\"token-display\" cewt-ref=\"poolsTo\"></span>\n    </div>\n  </td>\n\n  <td>\n    <div class=\"badge\">\n      <span is=\"token-display\" cewt-ref=\"exchangeRateFrom\"></span>\n      <span class=\"equals\">=</span>\n      <span is=\"token-display\" cewt-ref=\"exchangeRateTo\"></span>\n    </div>\n  </td>\n\n  <td>\n    <div class=\"total-deposits\">\n      <span class=\"badge\" is=\"token-display\" cewt-ref=\"totalDepositsFrom\"></span>\n      <span class=\"badge\" is=\"token-display\" cewt-ref=\"totalDepositsTo\"></span>\n    </div>\n  </td>\n\n  <td>\n    <span cewt-ref=\"feeRate\">--</span>\n  </td>\n\n  <td>\n    <span cewt-ref=\"apy\">--</span>\n  </td>\n\n  <td>\n    <i class=\"cicon cicon-size-small cicon-fantasy-chevron-right primary cicon-gradient\"></i>\n  </td>\n";
	}
	return _templatePoolItemComponent;
}
export class PoolItemComponentAutogen extends HTMLTableRowElement {
	readonly refs: PoolItemComponentRefs;
	constructor() {
		super();
		if (this.childElementCount == 0) {
			this.appendChild(
				getPoolItemComponentTemplate()
					.content
					.cloneNode(true)
			);
		}
		this.setAttribute("is", "pool-item-component"); // allow for easy query selecting
		this.refs = new PoolItemComponentRefs(this);
	}
	connectedCallback() {
		// To be overridden by child class
	}
	disconnectedCallback() {
		// To be overridden by child class
	}
	adoptedCallback() {
		// To be overridden by child class
	}
	public static registerElement() {
		customElements.define("pool-item-component", this, { extends: "tr"});
	}
}
