/**
 * DO NOT EDIT YOURSELF!
 * This file was automatically generated by json-schema-to-typescript.
 * The source schema json was automatically generated by cosmwasm-schema during the contract build.
 * The Rust code is the source of truth! Re-run the whole build if this file is outdated.
 **/

/**
 * This structure describes a custom struct to return a query response containing the base contract configuration.
 */
export interface ConfigResponse {
  /**
   * The Astroport factory contract address
   */
  astroport_factory: string;
}
