// auto-generated by C.E.W.T.
// DO NOT EDIT BY HAND!!
export class SwapComponentRefs {
	#element: HTMLElement | ShadowRoot;
	constructor(element: HTMLElement | ShadowRoot) {
		this.#element = element;
	}
	#fromToken?: HTMLDivElement;
	get fromToken() {
		if (this.#fromToken === undefined) {
			this.#fromToken = this.#element.querySelector("[cewt-ref=\"from-token\"]:not(:scope [is] *)")!;
		}
		return this.#fromToken;
	}
	#toToken?: HTMLDivElement;
	get toToken() {
		if (this.#toToken === undefined) {
			this.#toToken = this.#element.querySelector("[cewt-ref=\"to-token\"]:not(:scope [is] *)")!;
		}
		return this.#toToken;
	}
}
let _templateSwapComponent: HTMLTemplateElement | null = null;
function getSwapComponentTemplate(): HTMLTemplateElement {
	if (_templateSwapComponent == null) {
		 _templateSwapComponent = document.createElement("template")
		 _templateSwapComponent.innerHTML = "\n  <div cewt-ref=\"from-token\"></div>\n  <button class=\"fantasy-circular arrow\">\n    <span class=\"cicon cicon-size-medium cicon-gradient cicon-fantasy-arrow-down primary\"></span>\n  </button>\n  <div cewt-ref=\"to-token\"></div>\n";
	}
	return _templateSwapComponent;
}
export class SwapComponentAutogen extends HTMLDivElement {
	readonly refs: SwapComponentRefs;
	constructor() {
		super();
		if (this.childElementCount == 0) {
			this.appendChild(
				getSwapComponentTemplate()
					.content
					.cloneNode(true)
			);
		}
		this.setAttribute("is", "swap-component"); // allow for easy query selecting
		this.refs = new SwapComponentRefs(this);
	}
	connectedCallback() {
		// To be overridden by child class
	}
	disconnectedCallback() {
		// To be overridden by child class
	}
	adoptedCallback() {
		// To be overridden by child class
	}
	public static registerElement() {
		customElements.define("swap-component", this, { extends: "div"});
	}
}
