// auto-generated by C.E.W.T.
// DO NOT EDIT BY HAND!!
export class SwapComponentRefs {
	#element: HTMLElement | ShadowRoot;
	constructor(element: HTMLElement | ShadowRoot) {
		this.#element = element;
	}
	#balanceAmount?: HTMLSpanElement;
	get balanceAmount() {
		if (this.#balanceAmount === undefined) {
			this.#balanceAmount = this.#element.querySelector("[cewt-ref=\"balance-amount\"]:not(:scope [is] *)")!;
		}
		return this.#balanceAmount;
	}
	#balanceAmountSpinner?: HTMLSpanElement;
	get balanceAmountSpinner() {
		if (this.#balanceAmountSpinner === undefined) {
			this.#balanceAmountSpinner = this.#element.querySelector("[cewt-ref=\"balance-amount-spinner\"]:not(:scope [is] *)")!;
		}
		return this.#balanceAmountSpinner;
	}
	#fromToken?: HTMLDivElement;
	get fromToken() {
		if (this.#fromToken === undefined) {
			this.#fromToken = this.#element.querySelector("[cewt-ref=\"from-token\"]:not(:scope [is] *)")!;
		}
		return this.#fromToken;
	}
	#availableAmount?: HTMLSpanElement;
	get availableAmount() {
		if (this.#availableAmount === undefined) {
			this.#availableAmount = this.#element.querySelector("[cewt-ref=\"available-amount\"]:not(:scope [is] *)")!;
		}
		return this.#availableAmount;
	}
	#availableAmountSpinner?: HTMLSpanElement;
	get availableAmountSpinner() {
		if (this.#availableAmountSpinner === undefined) {
			this.#availableAmountSpinner = this.#element.querySelector("[cewt-ref=\"available-amount-spinner\"]:not(:scope [is] *)")!;
		}
		return this.#availableAmountSpinner;
	}
	#toToken?: HTMLDivElement;
	get toToken() {
		if (this.#toToken === undefined) {
			this.#toToken = this.#element.querySelector("[cewt-ref=\"to-token\"]:not(:scope [is] *)")!;
		}
		return this.#toToken;
	}
}
let _templateSwapComponent: HTMLTemplateElement | null = null;
function getSwapComponentTemplate(): HTMLTemplateElement {
	if (_templateSwapComponent == null) {
		 _templateSwapComponent = document.createElement("template")
		 _templateSwapComponent.innerHTML = "\n  <div class=\"labels-row\">\n    <span>From:</span>\n    <div>\n      Balance: <span cewt-ref=\"balance-amount\">0</span>\n      <span cewt-ref=\"balance-amount-spinner\" class=\"loading-spinner-inline\" style=\"display: none;\"></span>\n    </div>\n  </div>\n\n  <div cewt-ref=\"from-token\"></div>\n\n  <button class=\"fantasy-circular arrow\">\n    <span class=\"cicon cicon-size-medium cicon-gradient cicon-fantasy-arrow-down primary\"></span>\n  </button>\n\n  <div class=\"labels-row\">\n    <span>To:</span>\n    <div>\n      Available: <span cewt-ref=\"available-amount\">0</span>\n      <span cewt-ref=\"available-amount-spinner\" class=\"loading-spinner-inline\" style=\"display: none;\"></span>\n    </div>\n  </div>\n\n  <div cewt-ref=\"to-token\"></div>\n";
	}
	return _templateSwapComponent;
}
export class SwapComponentAutogen extends HTMLDivElement {
	readonly refs: SwapComponentRefs;
	constructor() {
		super();
		if (this.childElementCount == 0) {
			this.appendChild(
				getSwapComponentTemplate()
					.content
					.cloneNode(true)
			);
		}
		this.setAttribute("is", "swap-component"); // allow for easy query selecting
		this.refs = new SwapComponentRefs(this);
	}
	connectedCallback() {
		// To be overridden by child class
	}
	disconnectedCallback() {
		// To be overridden by child class
	}
	adoptedCallback() {
		// To be overridden by child class
	}
	public static registerElement() {
		customElements.define("swap-component", this, { extends: "div"});
	}
}
