// auto-generated by acetewm
export class SwapComponentSlots {
	private _element: HTMLElement;
	constructor(element: HTMLElement) {
		this._element = element;
	}
	private _title?: HTMLSpanElement;
	get title() {
		if (this._title === undefined) {
			this._title = this._element.querySelector("[slot=\"title\"]") ?? document.createElement("span");
			this._title.slot = "title";
			this._element.appendChild(this._title);
		}
		return this._title;
	}
}
export class SwapComponentRefs {
	private _element: HTMLElement;
	constructor(element: HTMLElement) {
		this._element = element;
	}
	private _tradeInput?: HTMLFormElement;
	get tradeInput() {
		if (this._tradeInput === undefined) {
			this._tradeInput = this._element.querySelector("[ace-ref=\"trade-input\"]")!;
		}
		return this._tradeInput;
	}
}
export class SwapComponentAutogen extends HTMLElement {
	readonly slots: SwapComponentSlots;
	readonly refs: SwapComponentRefs;
	constructor() {
		super();
		const shadowRoot = this.attachShadow({ mode: "open" });
		shadowRoot.appendChild(
			(document.getElementById("ace-template-swap-component") as HTMLTemplateElement)
				.content
				.cloneNode(true)
		);
		this.slots = new SwapComponentSlots(this);
		this.refs = new SwapComponentRefs(this);
	}
	public static registerElement() {
		customElements.define("swap-component", this);
	}
}
