// auto-generated by C.E.W.T.
// DO NOT EDIT BY HAND!!
export class PoolDialogComponentRefs {
	#element: HTMLElement | ShadowRoot;
	constructor(element: HTMLElement | ShadowRoot) {
		this.#element = element;
	}
	#poolName?: HTMLSpanElement;
	get poolName() {
		if (this.#poolName === undefined) {
			this.#poolName = this.#element.querySelector("[cewt-ref=\"pool-name\"]:not(:scope [is] *)")!;
		}
		return this.#poolName;
	}
}
let _templatePoolDialogComponent: HTMLTemplateElement | null = null;
function getPoolDialogComponentTemplate(): HTMLTemplateElement {
	if (_templatePoolDialogComponent == null) {
		 _templatePoolDialogComponent = document.createElement("template")
		 _templatePoolDialogComponent.innerHTML = "\n  <h1>Pool</h1>\n  <span cewt-ref=\"pool-name\"></span>\n";
	}
	return _templatePoolDialogComponent;
}
export class PoolDialogComponentAutogen extends HTMLDialogElement {
	readonly refs: PoolDialogComponentRefs;
	constructor() {
		super();
		if (this.childElementCount == 0) {
			this.appendChild(
				getPoolDialogComponentTemplate()
					.content
					.cloneNode(true)
			);
		}
		this.setAttribute("is", "pool-dialog-component"); // allow for easy query selecting
		this.refs = new PoolDialogComponentRefs(this);
	}
	connectedCallback() {
		// To be overridden by child class
	}
	disconnectedCallback() {
		// To be overridden by child class
	}
	adoptedCallback() {
		// To be overridden by child class
	}
	public static registerElement() {
		customElements.define("pool-dialog-component", this, { extends: "dialog"});
	}
}
