// auto-generated by C.E.W.T.
// DO NOT EDIT BY HAND!!
export class GovernanceComponentRefs {
	#element: HTMLElement | ShadowRoot;
	constructor(element: HTMLElement | ShadowRoot) {
		this.#element = element;
	}
	#log?: HTMLTextAreaElement;
	get log() {
		if (this.#log === undefined) {
			this.#log = this.#element.querySelector("[cewt-ref=\"log\"]:not(:scope [is] *)")!;
		}
		return this.#log;
	}
}
let _templateGovernanceComponent: HTMLTemplateElement | null = null;
function getGovernanceComponentTemplate(): HTMLTemplateElement {
	if (_templateGovernanceComponent == null) {
		 _templateGovernanceComponent = document.getElementById("cewt-template-governance-component") as HTMLTemplateElement;
	}
	return _templateGovernanceComponent;
}
export class GovernanceComponentAutogen extends HTMLDivElement {
	readonly refs: GovernanceComponentRefs;
	constructor() {
		super();
		if (this.childElementCount == 0) {
			this.appendChild(
				getGovernanceComponentTemplate()
					.content
					.cloneNode(true)
			);
		}
		this.setAttribute("is", "governance-component"); // allow for easy query selecting
		this.refs = new GovernanceComponentRefs(this);
	}
	connectedCallback() {
		// To be overridden by child class
	}
	disconnectedCallback() {
		// To be overridden by child class
	}
	adoptedCallback() {
		// To be overridden by child class
	}
	public static registerElement() {
		customElements.define("governance-component", this, { extends: "div"});
	}
}
