import { SeiChainId } from "@crownfi/sei-utils";

const CHAIN_ID = process.env.CHAIN_ID as SeiChainId;
const POOL_FACTORY_CONTRACT_ADDRESS = process.env.POOL_FACTORY_CONTRACT_ADDRESS;
const ROUTER_CONTRACT_ADDRESS = process.env.ROUTER_CONTRACT_ADDRESS;
const SLIPPAGE_TOLERANCE_PERCENTAGE = process.env.SLIPPAGE_TOLERANCE_PERCENTAGE;

if (!CHAIN_ID ||
    !POOL_FACTORY_CONTRACT_ADDRESS ||
    !ROUTER_CONTRACT_ADDRESS ||
    !SLIPPAGE_TOLERANCE_PERCENTAGE)
  throw new Error("Missing environment variables");

if (isNaN(+SLIPPAGE_TOLERANCE_PERCENTAGE))
  throw new Error("SLIPPAGE_TOLERANCE_PERCENTAGE must be a number");


export const env = {
  CHAIN_ID,
  POOL_FACTORY_CONTRACT_ADDRESS,
  ROUTER_CONTRACT_ADDRESS,
  SLIPPAGE_TOLERANCE_PERCENTAGE: +SLIPPAGE_TOLERANCE_PERCENTAGE,
};