/**
 * DO NOT EDIT YOURSELF!
 * This file was automatically generated by json-schema-to-typescript.
 * The source schema json was automatically generated by cosmwasm-schema during the contract build.
 * The Rust code is the source of truth! Re-run the whole build if this file is outdated.
 **/

/**
 * This structure holds the parameters used for creating a contract.
 */
export interface InstantiateMsg {
  /**
   * The astroport factory contract address
   */
  astroport_factory: string;
}
